### PR TITLE
Move tests folder

### LINKED ISSUE #98: Move tests folder at the root of the repo
see https://github.com/Billingegroup/cookiecutter/issues/114 for more details

### PR DESCRIPTION
**Pull request by yucongalicechen**
closes #98

### CODE REVIEW

**Comment by bobleesj** [comment]
@yucongalicechen 

The CI fails because the installed package is unable to find example data.

Please add a line `MANIFEST.in` to import the test data as well.

From

```
recursive-exclude * __pycache__
```

to

```
recursive-include src/diffpy/labpdfproc/data *
recursive-exclude * __pycache__
```

**Comment by bobleesj** [comment]
So, to mimic the CI behavior, you can run `pytest -vv` after `pip install .` instead of `pip install -e .`. 

If you use `pip install .`, you can confirm that the you are running the tests from the installed package located in `miniconda3`, etc.

**Comment by yucongalicechen** [comment]
thanks for the comment! @bobleesj

**Comment by bobleesj** [comment]
@yucongalicechen Just a quick heads up that we might do a quick re-cookiecutter for all diffpy projects we have all the issues addressed here: https://github.com/Billingegroup/cookiecutter/milestone/6

Since all the tests are running smoothly at the top directory level, it will be very easy!

**Comment by yucongalicechen** [comment]
I'm adding back labpdfproc command here because I notice it disappears again on our main branch, but I remembered adding it back in one of the previous PRs... not sure what happened.
@sbillinge I think this PR is ready for review, thanks!

**Review by sbillinge — COMMENTED** [review]
It looks good.  We should be able to delete __init__.py from the tests folder.  Please can you delete that and see if everything still passes?

Then I think it is ready, it looks good.

**Comment by yucongalicechen** [comment]
Deleted! :)

**Pull request merged**
