### PR TITLE
Precommit instructions in README

### PR DESCRIPTION
**Pull request by cadenmyers13**

### CODE REVIEW

**Review by sbillinge — COMMENTED** [review]
There still seems to be some issues with your workflows that is causing conflicts.  It looks as if you may have redone edits that were already in my merged PR and this is raising conflicts?  It may be easiest to blow this branch away again and redo the commits on a clean branch.

**Comment by sbillinge** [comment]
@cadenmyers13 I was able to merge your PR on pdfmorph, so that is good.  Here I suggest we close this PR and make a new one for the pre-commit things (I don't remember what you had to do there beyond what i already did, maybe nothing?  In that case no need to make a PR for that).  then another PR for the file-path changes.  Thanks so much.

**Comment by cadenmyers13** [comment]
@sbillinge I think just the formatting on the README needs to be fixed. its not showing codeblocks. Ill take care of that and create a PR

**Comment by sbillinge** [comment]
> @sbillinge I think just the formatting on the README needs to be fixed. its not showing codeblocks. Ill take care of that and create a PR

we may not need code blocks everywhere there, use your judgement.  To put code snippets inline just use back-quotes (see here for a deeper discussion: https://stackoverflow.com/questions/10870719/inline-code-highlighting-in-restructuredtext

**Comment by cadenmyers13** [comment]
> > @sbillinge I think just the formatting on the README needs to be fixed. its not showing codeblocks. Ill take care of that and create a PR
> 
> we may not need code blocks everywhere there, use your judgement. To put code snippets inline just use back-quotes (see here for a deeper discussion: https://stackoverflow.com/questions/10870719/inline-code-highlighting-in-restructuredtext

Yeah code snippets, not code blocks. That is what i mean 😆

**Pull request closed without merging**
