### PR TITLE
Use reusable GitHub CI workflows for test-on-pr and matrix-test CI files

### LINKED ISSUE #135: Use reusable GitHub CI workflows for `test-on-pr` and `matrix-test` once Gooey package Py313 is available on Conda-forge
### Problem

The `test-on-pr` and `matrix-test` CI .yml files in this repository have been modified to `pip install` all `pip.txt` dependencies to support `Gooey` while testing. Please see the PR here https://github.com/diffpy/diffpy.labpdfproc/pull/134

### Proposed solution

Once `Gooey` provides conda packages for Python 3.13, update the `test-on-pr` and `matrix-test` CI files using the Billinge group's reusable CI scripts.

### PR DESCRIPTION
**Pull request by yucongalicechen**
closes #135

### CODE REVIEW

**Comment by bobleesj** [comment]
@yucongalicechen thanks  unfortunately, there isn't py313 `gooey` available on conda-forge (yet). So it is expected to fail.

**Comment by yucongalicechen** [comment]
> @yucongalicechen thanks unfortunately, there isn't py313 `gooey` available on conda-forge (yet). So it is expected to fail.

Ahh gotcha. I'm trying to fix the error in the CI actually - is this the right place to check/edit?

**Comment by bobleesj** [comment]
> > @yucongalicechen thanks unfortunately, there isn't py313 `gooey` available on conda-forge (yet). So it is expected to fail.
> 
> Ahh gotcha. I'm trying to fix the error in the CI actually - is this the right place to check/edit?

Which error are you trying to fix?

```
tests/test_tools.py:7: in <module>
    from diffpy.labpdfproc.labpdfprocapp import get_args
/usr/share/miniconda/envs/test/lib/python3.13/site-packages/diffpy/labpdfproc/labpdfprocapp.py:4: in <module>
    from gooey import Gooey, GooeyParser
E   ModuleNotFoundError: No module named 'gooey'
```

This one?

**Comment by yucongalicechen** [comment]
> > > @yucongalicechen thanks unfortunately, there isn't py313 `gooey` available on conda-forge (yet). So it is expected to fail.
> > 
> > 
> > Ahh gotcha. I'm trying to fix the error in the CI actually - is this the right place to check/edit?
> 
> Which error are you trying to fix?
> 
> ```
> tests/test_tools.py:7: in <module>
>     from diffpy.labpdfproc.labpdfprocapp import get_args
> /usr/share/miniconda/envs/test/lib/python3.13/site-packages/diffpy/labpdfproc/labpdfprocapp.py:4: in <module>
>     from gooey import Gooey, GooeyParser
> E   ModuleNotFoundError: No module named 'gooey'
> ```
> 
> This one?

The CI issue here: https://github.com/diffpy/diffpy.labpdfproc/actions/runs/12215424294/job/34077353886

**Comment by bobleesj** [comment]
@yucongalicechen I tried to pin Wxpython to 4.2.2. for all of the matrix CI runs: https://github.com/bobleesj/diffpy.labpdfproc/actions/runs/12246303644/job/34161941093?pr=4

it appears only macos-13, py3.11 through 3.13 fails with the following err msg:

```
└─ wxpython 4.2.2  is not installable because it requires
   └─ __osx >=11.0 , which is missing on the system.
```

My understanding is that if we use `macos-13`, then we are using MacOS13, which means oxs >=13.0. I am afraid this needs to be checked with the devs of wxpython.

**Comment by bobleesj** [comment]
> > @yucongalicechen thanks unfortunately, there isn't py313 `gooey` available on conda-forge (yet). So it is expected to fail.
> 
> Ahh gotcha. I'm trying to fix the error in the CI actually - is this the right place to check/edit?

@yucongalicechen if you want to run the matrix CI, you can add `pull_request` under `matrix-and-codecov-on-merge-to-main.yml` 

from 

```
name: CI

on:
  push:
    branches:
      - main
  release:
    types:
      - prereleased
      - published
  workflow_dispatch:
```

to

```
name: CI

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - prereleased
      - published
  workflow_dispatch:
```

and then create a PR to your forked `main` branch (no merge) to see all of the matrix CI runs.

**Comment by yucongalicechen** [comment]
Thanks Bob! I will try running the CI on my end. For now I will close this PR and add an issue to fix CI in the future?

**Comment by bobleesj** [comment]
yeah we can re-open this PR once gooey supports py313 via conda-forge.

**Comment by yucongalicechen** [comment]
closed through new issue #142

**Comment by bobleesj** [comment]
@yucongalicechen 

Just sharing an update here. I was not able to reproduce the CI bug using my Intel Mac, with macOs 13.6.3, py3.13

```
urllib3                   2.2.3              pyhd8ed1ab_1    conda-forge
wxpython                  4.2.2           py313h6799360_3    conda-forge
wxwidgets                 3.2.6                h6e2ffcd_0    conda-forge
xorg-libxau               1.0.11               h00291cd_1    conda-for
```

It installed `wxpython` and pytest runs locally.

**Pull request closed without merging**
